argo-cd:
  dex:
    enabled: false
  applicationSet:
    enabled: false
  notifications:
    enabled: false
  server:
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
